package com.zqnt.sdk.client.connector.domains;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/** Optional metadata shared by Connector requests. Missing transaction data is generated by the SDK. */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ConnectorRequestContext {
    private String tid;
    private String sn;
    private String assetId;
    private String externalId;
    private String clientId;
    private String userId;
}
